
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import SideBar from "./component/Sidebar";
import { getSession } from "../actions/getUser";


const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();
      console.log(session?.user?.email);

  return (
    
        <div className="flex md:flex-row flex-col">
        <SideBar email={session?.user?.email} />
        {children}
        </div>
        
  );
}
